services:
  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - app-network
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:8080
    depends_on:
      - app

  app:
    build: 
      context: node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node index.js
    ports:
      - 3000:3000
    volumes:
      - ./node:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - ./dbdata:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
